creation_rules:
  - path_regex: .*\.sops\.yaml$
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    age: "age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp"
