# --- INFRASTRUCTURE CONFIG ---
UPDATE_SERVER_IP="10.10.20.100"
ADMIN_LXC_IP="10.10.20.20"
LOAD_BALANCER_IP="10.10.20.21" # The IP the Agents will talk to

# --- K3S CONFIG ---
CONTROL_PLANE_IPS="10.10.25.11 10.10.25.12"
AGENT_IPS="10.10.25.101 10.10.25.102"
K3S_TOKEN="super-secret-token-123"

# --- STORAGE CONFIG ---
POSTGRES_IP="10.10.25.250"
MINIO_IP="10.10.25.251"