apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4b8gNzTMViW8IVKQiL2RK5HAHGor+o0vip2gGbuZRwaw6/keQzY8lXm9djSRg3LIN4VB/PcBbrEu0L02af30rIPwVFEumqtxvP1BnvYRVEsK,iv:wSV0nxyAEPkby++hC8stmv8q5ag668hy64Vaqu0K4Vc=,tag:/hRB3MptQmKS3lLLevNReQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:tAiXdt0ym6WjP3lb1S5j0bAkJA/bH9r8n8rzc+yf0ArSiDGGUMiWPrbcL+BAOgBHA7mdXi8R8P6mOv2VoAFnx+ty+fnPcb2DLyyKGJXl4dJTB2nozBJewnVy+EGdEqQE5geSV+MBs9aLe9aeVKWUsVoR,iv:dLQt4gmeK6I3ZgPdvTa7j/PlhfO8abYFcLsmnhXxtX8=,tag:KH8A+pX3SzvMrd9N/aen8w==,type:str]
    #ENC[AES256_GCM,data:OBDLz7dILW0JPZeS9q6np10JCbpWOAy3FVNHbCrnWBhWJ+np+6vxMNyZ7wlqUUHy/xX0XsTxZA==,iv:Ph/rmXbX4i3N25MFjTXqwpeDnm0gzwbukm8/2dOx+m4=,tag:w6SpX6osV4WWHcF/qiGhXw==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:MZfUbnRrdopi/loCq8uzJ6KGpgdwy5N8ZdvmvKIctxhSpuQEV0x5m4XYlD4jeWsEw/QiEypxY5aSEvCfMfliEA==,iv:qSmXNgedHNiDGnfXojiAnILoIMqpj9KHevNK/kTN3iQ=,tag:rydAfhBr+KkiF13Jd1l4TA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5azFEaDhUeEVRMm1VNlZH
            d3dDdWFuWnNLSCt6NXZNTVd1MGdSR1R6VFZzCmVkaVFvb0RYNkdIcHdBdHJpVDB1
            UWQ1a1hYeHpMMTRQSWc4R0o2K3FPL2sKLS0tIGFIZzVaSk9MV2dyYmxseHVvRWtj
            M0ZOWUhnUTI1YmEzZkwvdEJlSmlRcmsKKdtCRWeJsEmtVj7i2YY3QHkjmoTi5Wx5
            0wkY3gmdbazyYfMExKDtdTKJRzdw4n69rEb5adrFBtRbrsmPZ5VwOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T21:30:01Z"
    mac: ENC[AES256_GCM,data:XYxHO+r00XU1VwyvA3OrNUh7wkENRFuyclYuLdYK5MeCrHoPjbMaKdyMZaH01F34c1zWLedTppUUNXfzzvDwpkcY3ycgIXgeQ3dFfQGlKGdZ0ZvnXhyp+bLOnpgBGK4xaSagEN8js5RynnVs33Aqr0VSLIyVdd/BXFFvHafLkoA=,iv:nr02rWdWhYtIWJy3IqDHDduUcIxFDrGYxHixW2/caWo=,tag:7gW6+saOca5kGxbs9I65ZA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
