apiVersion: v1
kind: Secret
metadata:
    name: vaultwarden-secret
    namespace: vaultwarden
type: Opaque
stringData:
    #ENC[AES256_GCM,data:4b8gNzTMViW8IVKQiL2RK5HAHGor+o0vip2gGbuZRwaw6/keQzY8lXm9djSRg3LIN4VB/PcBbrEu0L02af30rIPwVFEumqtxvP1BnvYRVEsK,iv:wSV0nxyAEPkby++hC8stmv8q5ag668hy64Vaqu0K4Vc=,tag:/hRB3MptQmKS3lLLevNReQ==,type:comment]
    DATABASE_URL: ENC[AES256_GCM,data:tAiXdt0ym6WjP3lb1S5j0bAkJA/bH9r8n8rzc+yf0ArSiDGGUMiWPrbcL+BAOgBHA7mdXi8R8P6mOv2VoAFnx+ty+fnPcb2DLyyKGJXl4dJTB2nozBJewnVy+EGdEqQE5geSV+MBs9aLe9aeVKWUsVoR,iv:dLQt4gmeK6I3ZgPdvTa7j/PlhfO8abYFcLsmnhXxtX8=,tag:KH8A+pX3SzvMrd9N/aen8w==,type:str]
    #ENC[AES256_GCM,data:OBDLz7dILW0JPZeS9q6np10JCbpWOAy3FVNHbCrnWBhWJ+np+6vxMNyZ7wlqUUHy/xX0XsTxZA==,iv:Ph/rmXbX4i3N25MFjTXqwpeDnm0gzwbukm8/2dOx+m4=,tag:w6SpX6osV4WWHcF/qiGhXw==,type:comment]
    ADMIN_TOKEN: ENC[AES256_GCM,data:WVc74s+SYOiPKyfrq++bSFl7mWZ5iWD56s7Dj0e18+Wn,iv:+LaPQ4GnTrIOUpk5Vk5ZruRO9GekcjXHgu4/m4i2K7k=,tag:EfnDB/M9D3TZEf6idYvi8w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5azFEaDhUeEVRMm1VNlZH
            d3dDdWFuWnNLSCt6NXZNTVd1MGdSR1R6VFZzCmVkaVFvb0RYNkdIcHdBdHJpVDB1
            UWQ1a1hYeHpMMTRQSWc4R0o2K3FPL2sKLS0tIGFIZzVaSk9MV2dyYmxseHVvRWtj
            M0ZOWUhnUTI1YmEzZkwvdEJlSmlRcmsKKdtCRWeJsEmtVj7i2YY3QHkjmoTi5Wx5
            0wkY3gmdbazyYfMExKDtdTKJRzdw4n69rEb5adrFBtRbrsmPZ5VwOA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:50:09Z"
    mac: ENC[AES256_GCM,data:aIHaPC6xIlV2wNJ4/8IBauypGTf7BbOvseYMv8O0nLDe0MAB8NWNhDOCy0Kq38MQdz9tDJ4osCv+qm9+Tmfw6lNp1b7bzXPDek5cDqn0ihZJvqaaXddDQsbt+fX/eTSZq6MOaBUu2pP3nVGJyn/AzNNw+IhzornWc29y2mqAWqg=,iv:wiri52Fvxxi73tpmOuXrXlJn4xYn/TKRS8PIo7mQonI=,tag:rnpj9yF+IriCyG4yFbxmDw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
