apiVersion: v1
kind: Namespace
metadata:
  name: simplex
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: smp-server
  namespace: simplex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smp-server
  template:
    metadata:
      labels:
        app: smp-server
    spec:
      containers:
        - name: smp-server
          image: simplexchat/smp-server:latest
          args: ["start"]
          env:
            - name: ADDR
              value: "simplex.isarcloud.eu"
          ports:
            - containerPort: 5223
              protocol: TCP
            - containerPort: 443
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/opt/simplex
            - name: certs
              mountPath: /certificates
              readOnly: true
      volumes:
        - name: data
          emptyDir: {}
        - name: certs
          secret:
            secretName: simplex-tls
            items:
              - key: tls.crt
                path: simplex.isarcloud.eu.crt
              - key: tls.key
                path: simplex.isarcloud.eu.key
---
apiVersion: v1
kind: Service
metadata:
  name: smp-server
  namespace: simplex
spec:
  type: NodePort
  ports:
    - name: smp
      port: 5223
      nodePort: 32223
      protocol: TCP
    - name: smp-https
      port: 443
      nodePort: 32444
      protocol: TCP
  selector:
    app: smp-server
