apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik
  namespace: authentik
spec:
  rules:
    - host: auth.isarcloud.eu
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: authentik-service
                port:
                  number: 80
