# Rename this to authentik-secret.yaml, encrypt with kubeseal, and commit the sealed version!
apiVersion: v1
kind: Secret
metadata:
    name: authentik-env
    namespace: authentik
type: Opaque
stringData:
    AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:Bs5VhbzRXliPcF3yt12LwDGCFGVuXYpJvH71LcLgRc0TVsRblHsyknBbUOlXQ/nc/icc1daVZqSj/K7IVhm/Xdy3jpkoE8sKrZ7+Tl00guI=,iv:QfcIe0qTmJav23PlELPUGRAa3qmoXAU7gETx7nlb4gM=,tag:Whrc3v6Sk/U80Na+0BT8vA==,type:str]
    #ENC[AES256_GCM,data:iuhZ7GFuOII2KFdnbKAeA0jowmf5eDF3sjaPPxhJ55YuSy/8Pt6VzVKi6MYMpk728p7NP6TAOWMEOI7II9JLxYJj3DC04NE=,iv:MOfylbG3iVYLUTTA8kMoVa3BgC5RfYTdG0Hhf5YWUx4=,tag:k0mOowk+zMZRqQ9X3zAEYQ==,type:comment]
    AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:Rj97E8AXYWugsFKytaxqbDFf3xtySpJRj03abij70dxIPkXDSAi9pA==,iv:kVFEKjpq7dJLhCOqOpSYLzC/633I8kLBKLBiRcVee14=,tag:0j/dr0lDBZt7Im9u9H6KLQ==,type:str]
    AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:UVXVoQHpBvE/,iv:mMfqZSXiB8z9356nlFRl1JZXaJ7xx1yi0j7mBRxCwBg=,tag:h2NMPPFyYOOQUCeLauWRAQ==,type:str]
    AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:otsPFnsBH0bML8tAhIg=,iv:75u6FRGTZnwPBOgrwfEIPBMI+SXGD6xyIHVT5+qo+Ps=,tag:OgDABhBaSkiaOeMGqAgW2Q==,type:str]
    AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:BRZ9d8PCnSv3lJaZTGZGUCvZClqCHwEibRAnjU84Ij0=,iv:/VH8bLM4FybhgoWUE4aznSm9sQGdlQbBaekbGxYXd+s=,tag:e+Pa0vh7aQ7zb4HJnyqnnQ==,type:str]
    #ENC[AES256_GCM,data:rXVRcsQw7d0VCSj9lMexb45yDV1AQ7+BLVIiMbRn3hWJfHCi0uAJoCn0c+MgkIpcekBDQV4+ySIAoHQgO3K8zOJFPPiyPk/k3lwEhJkS,iv:/hrP9liA/rsuCWL4h22hSsYCTSwdW735L3zfvkxsEIM=,tag:kP7ifIcYqeTqy89GE1HbtQ==,type:comment]
    AUTHENTIK_REDIS__HOST: ENC[AES256_GCM,data:BAEutuR6RRIouoP4gKaATk0ewc4dXCOUXMWDb0ryzYS84dH3,iv:k7WP4rcFnSQedY0py881dSkmKe2PlaJebu/wy2psXP4=,tag:YQ0U2ruJO2i6q/S3p13ydw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoblBIeFZYK3RYeTdzZ0J5
            N2I4aXM3RmJ4cFh3dkplaVU5WHM2RHFtYWt3CktzKzBMWVBWcktQd2l1VkpxQ000
            TXFLbUZkMEFLVEdhMTc1OUVDNVliYW8KLS0tIDg4ZzBoN0ZlbXlHQ3dtT2ZYV3ZG
            aGxVNlhZRVYzd2lqWTRaRWVjK0FwRVUK39fzWGj80jMMPcT41ApIkccuyJ8IbXUJ
            6dj/rgEb8IEUTh5gG3YvAnVHq61VfSUC9pr2duIg7Vzs62fSkX0c0g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T01:08:16Z"
    mac: ENC[AES256_GCM,data:5x+4dNwyadoqlglfYBlcr19ijjME6rswGOt0exdxW1/olvHqqlyf4oa9YLnegOX3s6LwX6qusR4YsJ1cvO+p83lkJOGwIFZTVeBGg3nU/dUhyMwTc1TcsGEG7Tqo2vG84tQEJPFCCm2GAzAAjqwbWm5Dm2O4+cWk0v0HdoI51SM=,iv:sh9i0nepIRaTHniVtZ1nxu9fCyGPC36knRGbZzlGcJQ=,tag:kI8dGG6SYRY6b3gUQNIh9Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
