# Rename this to authentik-secret.yaml, encrypt with kubeseal, and commit the sealed version!
apiVersion: v1
kind: Secret
metadata:
  name: authentik-env
  namespace: authentik
type: Opaque
stringData:
  AUTHENTIK_SECRET_KEY: "generate-a-secure-random-string-here"
  # This assumes you have PostgreSQL running in the 'postgresql' namespace
  AUTHENTIK_POSTGRESQL__HOST: "postgres-rw.postgresql.svc.cluster.local"
  AUTHENTIK_POSTGRESQL__NAME: "authentik"
  AUTHENTIK_POSTGRESQL__USER: "authentik_user"
  AUTHENTIK_POSTGRESQL__PASSWORD: "your_secure_db_password"
  # Use MinIO or internal Redis if deployed. Using memory/local for this example.
  AUTHENTIK_REDIS__HOST: "redis-master.redis.svc.cluster.local"
