apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: authentik

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - authentik-pvc.yaml
  - authentik-secret.sops.yaml # In reality, use your kubeseal sealed-secret here
  - authentik-server.yaml
  - authentik-worker.yaml
  - authentik-service.yaml
  - redis.yaml
  - authentik-middleware.yaml

configMapGenerator:
  - name: authentik-blueprints
    files:
      - blueprints/embedded-outpost.yaml
      - blueprints/isarcloud-brand.yaml
