apiVersion: v1
kind: Secret
metadata:
    name: csi-s3-secret
    namespace: kube-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Hos/FCuHkzBlKlpwnkOsxffqe1loMiteAYHnN28+1VERz1OfKGT+6quaIU4A/OQR0P4=,iv:WgmQKTnW9Jo55C1rJHXTbajGSG18rAubWOPiWdAFW2k=,tag:y15fwmuGGvN9OH99CKu6pQ==,type:comment]
    accessKeyID: ENC[AES256_GCM,data:eG3AqxU=,iv:XpNRqH0Hsu+vd8bSeBe8nvZcGl/gCrUaFEfmd09talg=,tag:OtGFBlmJ2jIs2bltZVwfpQ==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:YoplqMh8uILNrhQuR1+YwrBWbZDKADou,iv:yntpsuykJQbZxvJ8YLWwn/iVeY0w0OsdrJiUGGUrQQc=,tag:hOBNCVy8K7hEM8a+8Hbiqg==,type:str]
    endpoint: ENC[AES256_GCM,data:ju+21A5uKWB4zKPfUkfHHz8CBWYqNqTU03js,iv:A679a120gyOPBJnuWuo/sQcoWCnRuTUlA2IShn+hb2A=,tag:0OD9wFNekXYcfWA3URNuAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDRNUWtmTXlQeEVObkJw
            WEdJd2dkNlZjTzFyWmUrRk9rSnczdFdPNTJvCjZORWcxaTE1bzlCU1FSUEZTQWs5
            TWN2S2dRZXJLRmR2NzVaRGRubUFnYnMKLS0tIHlMUlRJbWt2K0xRdDJhUjNNekJ1
            ZVhuRGJSMmVrV1VZR3p4dlpsTTVCb1UKzGcbZrDVnZduISh5CLk6kfjIbXhVk+Do
            mrV7L/DwElQrdEjc+Dx2CVeLpfrhR2EDzxWI/+el080N8Zv6gL2jnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T02:45:19Z"
    mac: ENC[AES256_GCM,data:PhSB2P63OEain69mFcwotSAQp/TTmzjcy1dZAE2oOb4AXBXZUMBk4S9JusKdVK2JBwsjqdylqPAS0gposMmgcI4+otAsp/7P/xVUJPCgwmniwef/rfvLmJot5Yje1cOChlQtKlWZBKY/twN72IGlnFXIZ+p9SNRPD+aynkQdqZs=,iv:uOdK7MMMLxp03Tu2y0KJtVT/7dFsut7n/ivZsr/GjsY=,tag:QsogmjDDu/Q6qWU6N9zYvQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
