apiVersion: v1
kind: Secret
metadata:
    name: csi-s3-secret
    namespace: kube-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:lKAnkR8mbcdTo0h4XNlE6u2ZXiYYnoCuIZ/UqIQuehyb8zQOBhjqxTDBXxX8ev36LvI=,iv:YJtJucKow+Zas8u/YThNGHJhNfi6I6h8y7/b7a/cDLM=,tag:yOrp5FcXHgtT2ghsoQ+iug==,type:comment]
    accessKeyID: ENC[AES256_GCM,data:UfdLxkmhC441Pw==,iv:nxQJn/GrZLzyHQ6GryewuR1NgzFdEEgcuXAo4k8+RoM=,tag:xph/i3ltVtydqsaBgpMdcA==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:7RSzEI6wmMWBQG9pRHUSg07sUb6G8kpkLlXxbx8g364=,iv:upWBeir+YQ39J+G8ISmWsCUfoC1xlBXa/V2fqer8cyA=,tag:mcTsThZPNA2rdAfOmv803w==,type:str]
    endpoint: ENC[AES256_GCM,data:f3iYWV9Qe/oOqnSIGzFtLxSs0iI2B9xBUe4=,iv:XysR4CoW9P82KMzoY0UyHpbe0O1Oj+ESntKIz2RfrcM=,tag:W5jnzjijkI99rMKTyXghwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBadTB3NFhVNXhlU1RuNDNK
            Q3dyd0E1REwzY0RZellRNXJ3V1VBOU1QMUJjCkhyUW52RDhDTVh5ejRoVXpQZkxC
            SUhSeHFtQjAvZVhoMU1EeEYzb0JiK00KLS0tIHlwMi9sVFBRY1FSMEhKSmsrV2dt
            TEpHME9zQ2E5S0dTVEprZGxjdnR2QWsK7PlsGUXHSMG6rEE5Bd5JpAATQEVup90v
            mW25GSeUKaEAEf2Ds7EzxAqyqHuyKS8PvyvudNtQM6P8h8KDiugxsg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-31T18:34:57Z"
    mac: ENC[AES256_GCM,data:jElTIOnDQUcGlcYYMWg+H5zll4IwGqxg1vi/u0DpgZn3zwLyx4ZBSS+xDnPMblBCZdSu1f07zQuQUewubV+uMemoh1ISpK411naZvJFtVSl8kwqDAF7tbSFAxEsWOdTi0GZ70+JwBMdXqKu4VHrkkh7uHz6Ody/4QiEXa8fntLQ=,iv:JQEsz+66U9y3JAfaxHblNC8qdT5qG0l7UqILOv+cwR4=,tag:u3ml+2TsgWMguiLU4buvGw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.9.1
