apiVersion: v1
kind: Secret
metadata:
    name: csi-s3-secret
    namespace: kube-system
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Hos/FCuHkzBlKlpwnkOsxffqe1loMiteAYHnN28+1VERz1OfKGT+6quaIU4A/OQR0P4=,iv:WgmQKTnW9Jo55C1rJHXTbajGSG18rAubWOPiWdAFW2k=,tag:y15fwmuGGvN9OH99CKu6pQ==,type:comment]
    accessKeyID: ENC[AES256_GCM,data:mfsd+Gdvr+kCQA==,iv:h006YVdZbAuJenOn/IXIIB7/q3tplU72EluZ9PiBbSk=,tag:RHw8jmQlzAoy7y9BFCMq9w==,type:str]
    secretAccessKey: ENC[AES256_GCM,data:3+DPa9ZRQSDVk9L38jCxWBcJBt0YsHslqMl3VwD43Ag=,iv:H/S8vwptV1ibE0kffLxSkFkLoAvYa28h3xYYmN1VLr8=,tag:iooM+Lgo13+zio0PhSg31A==,type:str]
    endpoint: ENC[AES256_GCM,data:ju+21A5uKWB4zKPfUkfHHz8CBWYqNqTU03js,iv:A679a120gyOPBJnuWuo/sQcoWCnRuTUlA2IShn+hb2A=,tag:0OD9wFNekXYcfWA3URNuAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqbDRNUWtmTXlQeEVObkJw
            WEdJd2dkNlZjTzFyWmUrRk9rSnczdFdPNTJvCjZORWcxaTE1bzlCU1FSUEZTQWs5
            TWN2S2dRZXJLRmR2NzVaRGRubUFnYnMKLS0tIHlMUlRJbWt2K0xRdDJhUjNNekJ1
            ZVhuRGJSMmVrV1VZR3p4dlpsTTVCb1UKzGcbZrDVnZduISh5CLk6kfjIbXhVk+Do
            mrV7L/DwElQrdEjc+Dx2CVeLpfrhR2EDzxWI/+el080N8Zv6gL2jnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T20:44:30Z"
    mac: ENC[AES256_GCM,data:QItwFDhTIlwnv9Mtjv0roxWDxjoCsfedaQjYc+UeJqhFW5gUzSXKvak7bJXyOrg+FDESl7pn60ds23a1TtRIkMV12b80HJxovJqgOZkitQk7GU3t1iY9lJUJEMzPq7SIWWelV3+/JzXwNUlR5TOJjAOMGJbkUHRVKsgsXKtuVzo=,iv:lVlq5v1wkgwSz9BbozZZdG0pMVOfHAnvFzAgPEJx2tg=,tag:EJdKq/BROX2/hxHjpel81A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
