apiVersion: v1
kind: Secret
metadata:
    name: owncloud-secret
    namespace: owncloud
type: Opaque
stringData:
    OWNCLOUD_DB_PASSWORD: ENC[AES256_GCM,data:RhZgl5G5xyXXVs8i5rXNBHtNBAyMW1oKdkujrXO0TI0=,iv:/BDLTI++vyxOIfx2bkHwc01jZlmdm8vXEMqA/9tpesg=,tag:ranmGxsTQiFrKF+O479CQw==,type:str]
    OWNCLOUD_ADMIN_USERNAME: ENC[AES256_GCM,data:LuSeKKA=,iv:wzTF73cIaapq/SKBu/NJubeis+nL7O1pMFL8Mk5SNwU=,tag:vPpE8PQpVZRk9Mk0Ygd9FA==,type:str]
    OWNCLOUD_ADMIN_PASSWORD: ENC[AES256_GCM,data:ujX4wBbyB27eyV8+2tqibaO0O1YWkvDw,iv:IJucb8Zd95kTpMJwy2WJnl2Y9k3cHOH2cG+xOvmJNhg=,tag:7MRp74NOjXm6WzXSLlXxSQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmdk1rbUJpb1JvaXRaRnQ2
            Tm5lTVNPVHk1OFJLckVvbXlOOVlkcWpKekNBCnlSYzhFTzNNR0hGcXUyRGQxTW1k
            aVBVbXFxeDJCOW93Y3JCMFUvZ0JUN1UKLS0tIGFkM01TRENNdi83YUFnQzQ1L01R
            YmNKY0dtME5MTHhRRVAyMVNpUFdHRXMKqEm2yBuoShdpsncFrohma8HfWNjLbrtM
            ZyPz9gVTqInCORU40/xpKeHC5J1xmJibp7sqCkVfG44I5hIs1k5bGg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T21:30:01Z"
    mac: ENC[AES256_GCM,data:BZ4a4fB/FF5n84grGw3okPFLHFGUakw4EYAZba6JRJZQq18sNgQEG7xTdFSIywiYIhvyqVkeLr0Zau6MZVvkbYX0qkMnvfparKiLg478XSwB2YfqBWHjn1GcAPFrReU8THeD0XBsX1n5t2RElgzN/sP7kz/5EkLem5hNsQ+WLDU=,iv:8df3poZHoIiH+ynNnTiUHtw35chibnm+dXLIXevdK9E=,tag:OvLncMD+zsjFaOQweq4bTg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
