apiVersion: v1
kind: Secret
metadata:
    name: immich-secret
    namespace: immich
type: Opaque
stringData:
    DB_PASSWORD: ENC[AES256_GCM,data:NKAv2FAJjXa5jeSc9128xkR10WGg2+yv4hDK66lnhjk=,iv:RY1T1rdxk4Iy9jo9pp/GK0XpiNaZs/MrqJf0DWZ0NFc=,tag:ecX/uCWbfJqbvsvzl1ah0Q==,type:str]
    DB_HOSTNAME: ENC[AES256_GCM,data:VIUHZ5Tep8sg,iv:gdq5YpMO85HbOuKlLAmO+chrzCDhSFPfJMTpm35eTgk=,tag:r4NnXF7IdrX+v31eRdJsQg==,type:str]
    DB_USERNAME: ENC[AES256_GCM,data:9KOGSX1V,iv:TFSBly8DZRe1e5SDI9MXgsmKtYRa/XRyVMNTNApmaXE=,tag:k0IF2Cuc6tz+CEFy6z8Y4Q==,type:str]
    DB_DATABASE_NAME: ENC[AES256_GCM,data:d0CQyZpd,iv:TkLL1X7sLu98548B2v8BXdnF1ci1CXJcYK0IyFIAUpw=,tag:quIZfwdSqWNLCspYkVwS/A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5TXlMMk9nSXYzL3RzN1Ar
            SXoxNHNTbTRiaWIyamcybGJxYUxXeW5uaHcwCmgwQTdsSTl6UW5SbGZNdlR2WEZP
            VXFyYk1tdFVJcFcrV3haRTFSTEVvVncKLS0tIGFJcjZtZ0J6YkNkb0YzOXV6M3g2
            ZzdZdVhpd3R4QXVPRzJIY3UyRU5Id1EKbymsoIFMC6thDETSaQDWkR0Pqn78CYj2
            TFQBcjWZNIj4SB/c54o++wFgSv1wwzywZ2KsyKXZDMhKd5XDh34pQg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T21:30:01Z"
    mac: ENC[AES256_GCM,data:WZFm/jkIOaI3L+Uad4BkqChmHyI9mfB+4BPZr8xjuLbPyWDWOUFRTZs0K23XsoJ8CVSe+89Sn4UhRkh6kmUfM86tbf1GOCwJcPVQMRdAc610+4268IYh1Fwl4C7DH9H7fb9wL422+4XlKu/v8qxKPG47zYpsVH1MzEcsqGLzomQ=,iv:Q7JdTKPmjCVEgRI0zEPjsVh5DWpVJukoucwyrh1FV2Y=,tag:jic6L0zm7saAjGiyO8fY0A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
