apiVersion: v1
kind: Secret
metadata:
    name: synapse-secret
    namespace: synapse
type: Opaque
stringData:
    #ENC[AES256_GCM,data:dRd1ua5SmyJHkByIVa+siucg1CDEenO3vjoRzjO0vCSsXFgrweEZFZKZxj7SiuuUEOiaxZ7yS8Yi67+yazwQVd1dPUYu,iv:tuh9fNptFuHJXuRE+TDUDziBm93ahg4wu7mcvsjbFno=,tag:ZsRnXa3xFMj06bweVxLv4A==,type:comment]
    SYNAPSE_POSTGRES_PASSWORD: ENC[AES256_GCM,data:asFDNfkhpFo9KW/0pjo2pBtlc0/fmbW8De+wcdOiuHo=,iv:lH36TuVDi2F47/R0P5JJw8Mg9WY0Otj0wKndQ9IkT9M=,tag:MVaSKPnEX6Lan7IdTLZ4Bw==,type:str]
    #ENC[AES256_GCM,data:MMyjchCo3fKcHFtxQ0ModmleTF26SQ==,iv:3/ZWaUhljQhSaTF6Ov3SjHz6QDlf8ixoitqOKo3b6Rk=,tag:eih/I1IbPMU7vr6avjl3JQ==,type:comment]
    SYNAPSE_MACAROON_SECRET_KEY: ENC[AES256_GCM,data:sutci1i8EQ44W2LdDNUTURRVc/k3BM0kNpK0fzfRw0wcFn4T6sP6I9UOvvjlAIUcUE6QcqbB+t2/9nKGtDwkGw==,iv:BJa9PkdJ1nI60omnw40A9bNC7Uv9MLGYC56tXT90M2s=,tag:GHA3Ga3Jwj+/wimNoG/DqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU01Hd0UrZk5lRzY1ZjQx
            QVg1UzdtUFExNmlGUHpUMmZVcXBHTDB4VlVrCklWTzdTZXkva2RrTFhqQWE2bHF4
            RWdaM0VnaGI4QkhUQVBPc0RDZXZpRm8KLS0tIHR1Q2x0N0MyUXh1Y2x6bmJyOU9r
            Q1graGJQUVJxK3VQMWZJVUdCR09JcE0KFm2tzp/QHHrYFoYSiZ3UUtgi1swjnd23
            fwbvhD9Sl18QLJQnLriwHA9dzWjssi1/Rm+GQmfc7Uop5CUqjuXR6A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T21:30:01Z"
    mac: ENC[AES256_GCM,data:82RwKNGDEeidKU/4p0A/pt4UGxOmju7/X7LJXcLIZNuMXdxWfP5QID4Ort6egNBo4PGJ4nXR/dGZd6mUWNSV/YN63Cj5XMPz9OzaVegbbLUJ7dK9Z5Nm8owtsPgy9LoXiC+NO/VyA2NX9aurJYYmd9a6GGJJgitpeBsD+SbyYY8=,iv:QPtwswFaufq+6DpK8fONk29qdOk6Zec7n9l0GJD8D+Y=,tag:uZNVywFnrW0EA9z5dkXf1g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
