mikrotik_password: ENC[AES256_GCM,data:euqLUmlmIl9BgQCA3UIB,iv:NiiwAjTdvjkqyHytLBhYOnwtJT7B4cG+ibJLMU8Nizs=,tag:S6Ny2Art29hCygqsfj3tWA==,type:str]
s3_endpoint: https://s3.your-offsite.example.com
s3_access_key: ENC[AES256_GCM,data:Hi9UynUkW4h5,iv:c9XpNRXRSD1uRSDduHs3Oihufmx4onDpLRHLtIqplIo=,tag:b6g7hmJ80zm2vKsIfIxtlg==,type:str]
s3_secret_key: ENC[AES256_GCM,data:mFK4k6LWJRiN,iv:Aut2Xg175d0LX6n5nnQewSJBaGP1/bhV4Qx+zvGYvWc=,tag:R4vudhMgEhAoNXgB5RxRKQ==,type:str]
s3_bucket: homelab-lxc-backups
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiM0NhRzFxTGkvZWVSL25p
            czMvTmRYR0tOMjh6bTBrMFZpMjIzQTNvaFZVCmEreUhlN0t5b1h3bElpR3NvVWVH
            d1BmNEJDdGRRYzgvd3Z5Y3JnVWFtR3cKLS0tIHZkZkFWOG9Ca0RoUHpxSEZQWVRV
            UFBLcHl6SFRzM0FRZERKQjBiaWNHbmcKmIF4hS2LIE0YWNu7pXl47gwERxEq8BLX
            Kojh+Vy5gQVE3KXWAyeXPsEuM0kD/W1fN5APDwdI/T26vzXjGx0yPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T21:15:19Z"
    mac: ENC[AES256_GCM,data:FFH1P0e2GZYxokllO71BI8T8ARXPTkRYGpYb8swMOiU11oIdm/ed1DxwPwg8G+MGJtrACsMLLLkd/MbIAyaCKFbe2sxu/gmWI7czdVN7vJYB/WJUsCUYtIEfkccCtpHfhTvPjRQMiB/psUs7qUQs02gpZvmOhgBtjpD7TD5F+VY=,iv:y1oS9QkygFlVYOBtd5Da604aeAqLPFExGnW7Y3zsh9g=,tag:5O1ctffMufc/tORnl+I/SQ==,type:str]
    pgp: []
    encrypted_regex: (password|secret|pass|key|token|credential)
    version: 3.8.1
