apiVersion: v1
kind: Secret
metadata:
    name: snipeit-secret
    namespace: snipeit
type: Opaque
stringData:
    APP_KEY: ENC[AES256_GCM,data:AROr4yZV3puwLLuvXdNd1UY1L0miR7TmZfmyVPpQapXsr9KGXMqUYoa1LzvIb5jS4ZpJ,iv:QVQ1cw2I3r4cDRyMvv0T2gRwA9X09P//4Wqk0fjLqv4=,tag:lbrz62bT4IoIrIQxL9VGpA==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:AygHh9AkTSmZiahhmbak6upGTPs9N/LEFtqjcJbeJRQ=,iv:0a3i/MhHpHMRK+iNMIzhABIsA82ZLpy3fBT2IFzu8rM=,tag:fA531lIe3mh77v7ZF5be8Q==,type:str]
    MYSQL_ROOT_PASSWORD: ENC[AES256_GCM,data:xpDA6rPhJuZlCaDL5l/o1wnuCDALfl2S2rKE3RAi+YI=,iv:ThRyp42FoD81Y4dnRkYP2SExY7wOSboz4zmOEAA9jtc=,tag:2fGofv5IDaQMHW1t/3MKuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjeStyL1ZmK2xMTkJZSnk1
            YzdkQjlFZmVNVWFFRnRKeFc5aktZaFBKdzJNCmtRRmYyN0hCaDMybnE0bllPd09q
            ZzVkTlRJVU1LK1d6b2pvalQ2dllCeFEKLS0tIEIrU2YxQXhSc001Q2pNNkV3YXhm
            YnlPWlYvUm1GY2UxOE9RRGRSY3Y1b1EKXRtssgTR+zY6UvSIC1SI8nF5yq1mt4F3
            LnO57dS0l61Qp5o04l+xxcJaUcRacx5SUMor9tmhqIF73/hu8ERsCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-08T15:00:06Z"
    mac: ENC[AES256_GCM,data:fWtXvIrjNTveVXz9MNzCSmDlpUO3htcEvz1KpxAgGf4fRYNBJ/lHV5r1UgrYB52/VDTqCn44H4qHiHp8n1E561471sLAqd2BXqX6bVtiUnqmwSDT/Jxa1XB7Tw+Vpm10bdalKxsypkXuOy6+oEyrebFsWIc4EFQZD07jZ7/Nmqs=,iv:MPTa87ff85cs8pFGxoURL2H99VkYWR+8amWuBgMmAYI=,tag:6dlkZgazrCFjx1BeN8Ou0Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.9.0
