apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Jgm/d5bSDngiPNe3K0J/SQTzfgCoJSPuPVA2d6FxAZAdqGMt00xsrp/OOwxz8Opwvi2PicgpNGQliYY8,iv:q7JHhhSsMb7vvTGWkSJuCaYqtolw/0yDqDQUfNQgEBs=,tag:yzp5LHTDL2thS/efqW8XuA==,type:comment]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:bJetRJQsblKny3qH9hjHTLmXi73YMAyGsTZkJ8eKNoQ=,iv:LOxtbD5HqyILhetv1C4nJHphRIVGiDsiX6XI6vAichg=,tag:Zk4GN3R9kxygvv1aKTSijg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:tVTV4iosfahfMpGt5+mVw5u+AA6G1xak1TkwuE25GIn5a/w2XvbkgDBhmqMlCt1iO/W/zL6aAeG+8qiA1FIWPw==,iv:HvOCrB9lMxG3C1diMDh8/xXBArBd8zsp6QLgWPlS3E8=,tag:I6VjnKmyPi6Jk8JXSF6nww==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:7oup+0I=,iv:Eas8AaTkbJL8Xiwah2GHYm4yCYnpShPAIv7XdCOi2Go=,tag:nwChGatmSQQbQXe+QqOchA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:v3m2U8PgVF9vpwiVyIHaDZo4k1ZmDUPM,iv:OhShxlYYU31/KtUmYiR/55vmrY+vCSv5L3DyGDzpHZA=,tag:zm7s6ErCs0XP1mGZw0QeJA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcVpIMTVmblZZYWtmU1Bs
            SUNQb2FQbVhnbEZOSDJpdGhxOU1kb3VIc0hNCjNmQS9CZ3p1bW5aM0dNNXd0QkMx
            VE9samowL0FMMXdxbmcwc0JSbjFMMkkKLS0tIHJjTXBHMHJjKzZVS3FFNkpvbkRS
            RFRManNFc3ZhTEYrc0RET05yQ2JLYm8Kiv21Iv6EVyj/saeurrZ/mXVK4xSSHblQ
            e8KIzxNtTui6k97/vtovSimufdY2nc3bvbAWMJa+FqXxB+y60QIP/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T21:30:01Z"
    mac: ENC[AES256_GCM,data:NlELwvkUag9ACXh2jx1WD9fDAA6yKjQO3zXMYUZBtoul8Ei4IdBDD5N0SuXcdKM6LfgwFdaQOQaABYPAx5NHh+jXxlt0JEbwjV3U9Lm9eQI4/A09hm9pLKlCdD9vZzXdxzJj6MV8o+qAQmOczBdbmuAIICt9y+S4ciz2H5FyyDM=,iv:C/RsuHYda/KcE+rPSXT1+FrYDfEQ0gmXw+o2pkUh/lU=,tag:Q9YTC3DUEwQ6vnJ/EGUAJA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
