apiVersion: v1
kind: Secret
metadata:
    name: paperless-secret
    namespace: paperless
type: Opaque
stringData:
    #ENC[AES256_GCM,data:Jgm/d5bSDngiPNe3K0J/SQTzfgCoJSPuPVA2d6FxAZAdqGMt00xsrp/OOwxz8Opwvi2PicgpNGQliYY8,iv:q7JHhhSsMb7vvTGWkSJuCaYqtolw/0yDqDQUfNQgEBs=,tag:yzp5LHTDL2thS/efqW8XuA==,type:comment]
    PAPERLESS_DBPASS: ENC[AES256_GCM,data:bJetRJQsblKny3qH9hjHTLmXi73YMAyGsTZkJ8eKNoQ=,iv:LOxtbD5HqyILhetv1C4nJHphRIVGiDsiX6XI6vAichg=,tag:Zk4GN3R9kxygvv1aKTSijg==,type:str]
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:cOxBWwIf/v6GwAEloNQTFC1VZi8=,iv:u12pETnHNpcpt3ErJS2DjRIItfg4hp+HAswLx9C3BRU=,tag:Vo/Eyth1jt0owvTrsq4pRg==,type:str]
    PAPERLESS_ADMIN_USER: ENC[AES256_GCM,data:7oup+0I=,iv:Eas8AaTkbJL8Xiwah2GHYm4yCYnpShPAIv7XdCOi2Go=,tag:nwChGatmSQQbQXe+QqOchA==,type:str]
    PAPERLESS_ADMIN_PASSWORD: ENC[AES256_GCM,data:b6iyJfpRtlEV/0jsBoLhi3RPiQToeSkk,iv:JKg423nOmElKVHQYhpNWWCRfFWamL/YxYaNkoeocs2Y=,tag:iuydrX/nT+gHkiBNO4sDYA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gnkmh0kwyds2ckzhe96cqjxg08llfgp8lkmxa3z9vgzd33s25pks0d00pp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVcVpIMTVmblZZYWtmU1Bs
            SUNQb2FQbVhnbEZOSDJpdGhxOU1kb3VIc0hNCjNmQS9CZ3p1bW5aM0dNNXd0QkMx
            VE9samowL0FMMXdxbmcwc0JSbjFMMkkKLS0tIHJjTXBHMHJjKzZVS3FFNkpvbkRS
            RFRManNFc3ZhTEYrc0RET05yQ2JLYm8Kiv21Iv6EVyj/saeurrZ/mXVK4xSSHblQ
            e8KIzxNtTui6k97/vtovSimufdY2nc3bvbAWMJa+FqXxB+y60QIP/Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-08-02T02:02:37Z"
    mac: ENC[AES256_GCM,data:saotT75nOTx3ycaCqUEXqbSrldhAEzUiMObq2y53aVjmdfOXSuOoJvqcHc36h1NSW51cbjXqnbcl9EYuMSZ61KMzGHu40DdmN9cfEb5LYe8RSqtWnYF2Dcb50oTwD0vXRM5ieU7EXpd3uLyE4GdpDW0xFaGyB/otIMZ3i+7oY/4=,iv:cLlAgjBvysQQzGLruXx6l3ISSWFxisQHx7YZT5NkSqA=,tag:NAN8teCGLh1gp62NlCQVIA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData|password|secret|pass|key|env|tokens|secrets|token)$
    version: 3.8.1
