#!/bin/bash
# admin-setup.sh - Aaron's Homelab Management Bootstrap
set -e

echo "=== Step 1: System Preparation ==="
apt update && apt upgrade -y
apt install git ansible make python3 curl nano -y

echo "=== Step 2: SSH Key Generation ==="
[ -f ~/.ssh/id_ed25519 ] || ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519 -N "" -q

echo "=== Step 3: Repository & Configuration ==="
[ -d "~/homelab" ] || git clone https://github.com/aaronschm/homelab.git ~/homelab

CONF_FILE="$HOME/homelab/cluster.conf"
# Sourcing it to get variables for the SSH config
if [ -f "$CONF_FILE" ]; then
    source "$CONF_FILE"
else
    echo "cluster.conf not found! Creating template..."
    # (Template creation logic here as per your original prompt)
fi

echo "=== Step 4: Generating SSH Config ==="
SSH_CONF="$HOME/.ssh/config"
echo "# Auto-generated by admin-setup.sh" > "$SSH_CONF"

# Helper function to append hosts
add_ssh_host() {
    local name=$1
    local ip=$2
    cat <<EOF >> "$SSH_CONF"
Host $name
    HostName $ip
    User root
    Port 2022
    IdentityFile ~/.ssh/id_ed25519

EOF
}

# Static entries
add_ssh_host "update-server" "$UPDATE_SERVER_IP"
add_ssh_host "load-balancer" "$LOAD_BALANCER_IP"
add_ssh_host "postgres" "$POSTGRES_IP"
add_ssh_host "minio" "$MINIO_IP"

# Dynamic entries for Clusters
i=1
for ip in $CONTROL_PLANE_IPS; do
    add_ssh_host "cp-$i" "$ip"
    ((i++))
done

i=1
for ip in $AGENT_IPS; do
    add_ssh_host "agent-$i" "$ip"
    ((i++))
done

chmod 600 "$SSH_CONF"
echo "✓ SSH config created. You can now use: ssh cp-1, ssh load-balancer, etc."

echo "=== Step 5: SSH Hardening Admin LXC ==="
bash ~/homelab/scripts/ssh-setup.sh

echo "=== Step 6: Hosting Assets for Update Server ==="
STAGING_DIR="/tmp/bootstrap_transfer"
mkdir -p "$STAGING_DIR"
cp -r ~/homelab/scripts/* "$STAGING_DIR/"
cp "$CONF_FILE" "$STAGING_DIR/"
cp ~/.ssh/id_ed25519.pub "$STAGING_DIR/admin_lxc.pub"

cd "$STAGING_DIR"
echo "Serving assets on port 8000 for 15 minutes..."
timeout 15m python3 -m http.server 8000