---
- name: Install AdGuard Home DNS
  hosts: adguard
  become: yes
  vars:
    adguard_version: "v0.107.52"
  tasks:
    - name: Download AdGuard Home
      unarchive:
        src: "https://github.com/AdguardTeam/AdGuardHome/releases/download/{{ adguard_version }}/AdGuardHome_linux_amd64.tar.gz"
        dest: /opt
        remote_src: yes
        creates: /opt/AdGuardHome/AdGuardHome

    - name: Install AdGuard Home as a service
      command: /opt/AdGuardHome/AdGuardHome -s install
      args:
        creates: /etc/systemd/system/AdGuardHome.service

    - name: Ensure AdGuard is started and enabled
      systemd:
        name: AdGuardHome
        state: started
        enabled: yes
